services:
  backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/expensive_db
    command: bash entrypoint.sh

  db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: expensive_db
    volumes:
      - expensive_db:/var/lib/postgresql/data

volumes:
  expensive_db:
