/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppMembersUserIdRouteImport } from './routes/_app/members/$userId'
import { Route as AppGroupsNewRouteImport } from './routes/_app/groups/new'
import { Route as AppGroupsGroupIdIndexRouteImport } from './routes/_app/groups/$groupId/index'
import { Route as AppGroupsGroupIdLedgersNewRouteImport } from './routes/_app/groups/$groupId/ledgers/new'
import { Route as AppGroupsGroupIdLedgersLedgerIdIndexRouteImport } from './routes/_app/groups/$groupId/ledgers/$ledgerId/index'
import { Route as AppGroupsGroupIdLedgersLedgerIdExpensesNewRouteImport } from './routes/_app/groups/$groupId/ledgers/$ledgerId/expenses/new'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersUserIdRoute = AppMembersUserIdRouteImport.update({
  id: '/members/$userId',
  path: '/members/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsNewRoute = AppGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdIndexRoute = AppGroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdLedgersNewRoute =
  AppGroupsGroupIdLedgersNewRouteImport.update({
    id: '/groups/$groupId/ledgers/new',
    path: '/groups/$groupId/ledgers/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsGroupIdLedgersLedgerIdIndexRoute =
  AppGroupsGroupIdLedgersLedgerIdIndexRouteImport.update({
    id: '/groups/$groupId/ledgers/$ledgerId/',
    path: '/groups/$groupId/ledgers/$ledgerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute =
  AppGroupsGroupIdLedgersLedgerIdExpensesNewRouteImport.update({
    id: '/groups/$groupId/ledgers/$ledgerId/expenses/new',
    path: '/groups/$groupId/ledgers/$ledgerId/expenses/new',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/members/$userId': typeof AppMembersUserIdRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/groups/$groupId/ledgers/new': typeof AppGroupsGroupIdLedgersNewRoute
  '/groups/$groupId/ledgers/$ledgerId/': typeof AppGroupsGroupIdLedgersLedgerIdIndexRoute
  '/groups/$groupId/ledgers/$ledgerId/expenses/new': typeof AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/members/$userId': typeof AppMembersUserIdRoute
  '/groups': typeof AppGroupsIndexRoute
  '/groups/$groupId': typeof AppGroupsGroupIdIndexRoute
  '/groups/$groupId/ledgers/new': typeof AppGroupsGroupIdLedgersNewRoute
  '/groups/$groupId/ledgers/$ledgerId': typeof AppGroupsGroupIdLedgersLedgerIdIndexRoute
  '/groups/$groupId/ledgers/$ledgerId/expenses/new': typeof AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/groups/new': typeof AppGroupsNewRoute
  '/_app/members/$userId': typeof AppMembersUserIdRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
  '/_app/groups/$groupId/ledgers/new': typeof AppGroupsGroupIdLedgersNewRoute
  '/_app/groups/$groupId/ledgers/$ledgerId/': typeof AppGroupsGroupIdLedgersLedgerIdIndexRoute
  '/_app/groups/$groupId/ledgers/$ledgerId/expenses/new': typeof AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/groups/new'
    | '/members/$userId'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/ledgers/new'
    | '/groups/$groupId/ledgers/$ledgerId/'
    | '/groups/$groupId/ledgers/$ledgerId/expenses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/groups/new'
    | '/members/$userId'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/ledgers/new'
    | '/groups/$groupId/ledgers/$ledgerId'
    | '/groups/$groupId/ledgers/$ledgerId/expenses/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/home'
    | '/_app/profile'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_app/groups/new'
    | '/_app/members/$userId'
    | '/_app/groups/'
    | '/_app/groups/$groupId/'
    | '/_app/groups/$groupId/ledgers/new'
    | '/_app/groups/$groupId/ledgers/$ledgerId/'
    | '/_app/groups/$groupId/ledgers/$ledgerId/expenses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$userId': {
      id: '/_app/members/$userId'
      path: '/members/$userId'
      fullPath: '/members/$userId'
      preLoaderRoute: typeof AppMembersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/new': {
      id: '/_app/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AppGroupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId/': {
      id: '/_app/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId/ledgers/new': {
      id: '/_app/groups/$groupId/ledgers/new'
      path: '/groups/$groupId/ledgers/new'
      fullPath: '/groups/$groupId/ledgers/new'
      preLoaderRoute: typeof AppGroupsGroupIdLedgersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId/ledgers/$ledgerId/': {
      id: '/_app/groups/$groupId/ledgers/$ledgerId/'
      path: '/groups/$groupId/ledgers/$ledgerId'
      fullPath: '/groups/$groupId/ledgers/$ledgerId/'
      preLoaderRoute: typeof AppGroupsGroupIdLedgersLedgerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId/ledgers/$ledgerId/expenses/new': {
      id: '/_app/groups/$groupId/ledgers/$ledgerId/expenses/new'
      path: '/groups/$groupId/ledgers/$ledgerId/expenses/new'
      fullPath: '/groups/$groupId/ledgers/$ledgerId/expenses/new'
      preLoaderRoute: typeof AppGroupsGroupIdLedgersLedgerIdExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppGroupsNewRoute: typeof AppGroupsNewRoute
  AppMembersUserIdRoute: typeof AppMembersUserIdRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppGroupsGroupIdIndexRoute: typeof AppGroupsGroupIdIndexRoute
  AppGroupsGroupIdLedgersNewRoute: typeof AppGroupsGroupIdLedgersNewRoute
  AppGroupsGroupIdLedgersLedgerIdIndexRoute: typeof AppGroupsGroupIdLedgersLedgerIdIndexRoute
  AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute: typeof AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppGroupsNewRoute: AppGroupsNewRoute,
  AppMembersUserIdRoute: AppMembersUserIdRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppGroupsGroupIdIndexRoute: AppGroupsGroupIdIndexRoute,
  AppGroupsGroupIdLedgersNewRoute: AppGroupsGroupIdLedgersNewRoute,
  AppGroupsGroupIdLedgersLedgerIdIndexRoute:
    AppGroupsGroupIdLedgersLedgerIdIndexRoute,
  AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute:
    AppGroupsGroupIdLedgersLedgerIdExpensesNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
